<<<<<<< HEAD
delete from servicios;
delete from caminosalternos;
delete from caminosExcepcion;
delete from poscondiciones;
delete from precondiciones;
delete from entidades;
delete from CasoDeUsoEntity ;


insert into casodeusoentity (id, nombre, documentacion, pruebas) values (1, 'Cornelius', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (2, 'Howey', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (3, 'Daisie', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (4, 'Weston', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (5, 'Rodrick', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (6, 'Almire', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (7, 'Genevieve', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (8, 'Noell', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (9, 'Ernie', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (10, 'Jacquette', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (11, 'Abbie', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (12, 'Christi', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (13, 'Miguela', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (14, 'Ethan', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (15, 'Reinwald', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (16, 'Armin', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (17, 'Rogers', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (18, 'Benjamin', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (19, 'Clemente', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 0);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (20, 'Ameline', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (21, 'Lina', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (22, 'Roxi', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (23, 'Mose', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (24, 'Arabele', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
insert into casodeusoentity (id, nombre, documentacion, pruebas) values (25, 'Ad', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0);


insert into servicios (servicios) values ('Ara chloroptera');
insert into servicios (servicios) values ('Spheniscus mendiculus');
insert into servicios (servicios) values ('Ardea golieth');
insert into servicios (servicios) values ('Anathana ellioti');
insert into servicios (servicios) values ('Trichosurus vulpecula');
insert into servicios (servicios) values ('Potorous tridactylus');
insert into servicios (servicios) values ('Phasianus colchicus');
insert into servicios (servicios) values ('Rhea americana');
insert into servicios (servicios) values ('Potos flavus');
insert into servicios (servicios) values ('Zonotrichia capensis');
insert into servicios (servicios) values ('Upupa epops');
insert into servicios (servicios) values ('Colobus guerza');
insert into servicios (servicios) values ('Varanus albigularis');
insert into servicios (servicios) values ('Eubalaena australis');
insert into servicios (servicios) values ('Rhea americana');
insert into servicios (servicios) values ('Varanus salvator');
insert into servicios (servicios) values ('Picoides pubescens');
insert into servicios (servicios) values ('Gekko gecko');
insert into servicios (servicios) values ('Falco peregrinus');
insert into servicios (servicios) values ('Genetta genetta');
insert into servicios (servicios) values ('Erethizon dorsatum');
insert into servicios (servicios) values ('Dasypus novemcinctus');
insert into servicios (servicios) values ('Varanus sp.');
insert into servicios (servicios) values ('Oncorhynchus nerka');
insert into servicios (servicios) values ('Canis lupus');

insert into entidades (entidades) values ('Argalis');
insert into entidades (entidades) values ('Sockeye salmon');
insert into entidades (entidades) values ('Red-knobbed coot');
insert into entidades (entidades) values ('Cockatoo, red-tailed');
insert into entidades (entidades) values ('Stanley crane');
insert into entidades (entidades) values ('Sable antelope');
insert into entidades (entidades) values ('Red-necked wallaby');
insert into entidades (entidades) values ('American racer');
insert into entidades (entidades) values ('Duck, comb');
insert into entidades (entidades) values ('Asian elephant');
insert into entidades (entidades) values ('Sea birds (unidentified)');
insert into entidades (entidades) values ('Kangaroo, western grey');
insert into entidades (entidades) values ('Beisa oryx');
insert into entidades (entidades) values ('Toddy cat');
insert into entidades (entidades) values ('Crab, sally lightfoot');
insert into entidades (entidades) values ('Lion, australian sea');
insert into entidades (entidades) values ('Gerenuk');
insert into entidades (entidades) values ('Water moccasin');
insert into entidades (entidades) values ('Capuchin, brown');
insert into entidades (entidades) values ('Woodpecker, downy');
insert into entidades (entidades) values ('Praying mantis (unidentified)');
insert into entidades (entidades) values ('Spotted-tailed quoll');
insert into entidades (entidades) values ('Western spotted skunk');
insert into entidades (entidades) values ('Eagle, tawny');
insert into entidades (entidades) values ('Blue catfish');

insert into caminosalternos (caminosalternos) values ('Ford');
insert into caminosalternos (caminosalternos) values ('Suzuki');
insert into caminosalternos (caminosalternos) values ('Ford');
insert into caminosalternos (caminosalternos) values ('Mercury');
insert into caminosalternos (caminosalternos) values ('Kia');
insert into caminosalternos (caminosalternos) values ('Ford');
insert into caminosalternos (caminosalternos) values ('Saab');
insert into caminosalternos (caminosalternos) values ('Lincoln');
insert into caminosalternos (caminosalternos) values ('Mitsubishi');
insert into caminosalternos (caminosalternos) values ('Lexus');
insert into caminosalternos (caminosalternos) values ('Volkswagen');
insert into caminosalternos (caminosalternos) values ('GMC');
insert into caminosalternos (caminosalternos) values ('Jaguar');
insert into caminosalternos (caminosalternos) values ('Lexus');
insert into caminosalternos (caminosalternos) values ('Plymouth');
insert into caminosalternos (caminosalternos) values ('Suzuki');
insert into caminosalternos (caminosalternos) values ('Ford');
insert into caminosalternos (caminosalternos) values ('Volkswagen');
insert into caminosalternos (caminosalternos) values ('Honda');
insert into caminosalternos (caminosalternos) values ('Audi');
insert into caminosalternos (caminosalternos) values ('Acura');
insert into caminosalternos (caminosalternos) values ('Buick');
insert into caminosalternos (caminosalternos) values ('Mercedes-Benz');
insert into caminosalternos (caminosalternos) values ('Toyota');
insert into caminosalternos (caminosalternos) values ('Pontiac');

insert into caminosExcepcion (caminosExcepcion) values ('Sharable motivating success');
insert into caminosExcepcion (caminosExcepcion) values ('Open-architected bifurcated standardization');
insert into caminosExcepcion (caminosExcepcion) values ('Devolved tangible hardware');
insert into caminosExcepcion (caminosExcepcion) values ('De-engineered needs-based workforce');
insert into caminosExcepcion (caminosExcepcion) values ('User-friendly client-driven matrix');
insert into caminosExcepcion (caminosExcepcion) values ('Optional discrete customer loyalty');
insert into caminosExcepcion (caminosExcepcion) values ('Re-engineered fresh-thinking open architecture');
insert into caminosExcepcion (caminosExcepcion) values ('Self-enabling reciprocal policy');
insert into caminosExcepcion (caminosExcepcion) values ('Cross-group transitional database');
insert into caminosExcepcion (caminosExcepcion) values ('Open-architected value-added middleware');
insert into caminosExcepcion (caminosExcepcion) values ('Focused zero administration matrices');
insert into caminosExcepcion (caminosExcepcion) values ('Fundamental disintermediate website');
insert into caminosExcepcion (caminosExcepcion) values ('Quality-focused user-facing superstructure');
insert into caminosExcepcion (caminosExcepcion) values ('Enhanced tertiary benchmark');
insert into caminosExcepcion (caminosExcepcion) values ('Enterprise-wide user-facing initiative');
insert into caminosExcepcion (caminosExcepcion) values ('Total intangible analyzer');
insert into caminosExcepcion (caminosExcepcion) values ('Vision-oriented real-time architecture');
insert into caminosExcepcion (caminosExcepcion) values ('Virtual even-keeled synergy');
insert into caminosExcepcion (caminosExcepcion) values ('Extended zero administration benchmark');
insert into caminosExcepcion (caminosExcepcion) values ('Organic tertiary standardization');
insert into caminosExcepcion (caminosExcepcion) values ('Extended transitional hardware');
insert into caminosExcepcion (caminosExcepcion) values ('Assimilated static capacity');
insert into caminosExcepcion (caminosExcepcion) values ('User-centric intangible success');
insert into caminosExcepcion (caminosExcepcion) values ('Organic reciprocal instruction set');
insert into caminosExcepcion (caminosExcepcion) values ('Configurable scalable info-mediaries');

insert into poscondiciones (poscondiciones) values ('Turquoise');
insert into poscondiciones (poscondiciones) values ('Maroon');
insert into poscondiciones (poscondiciones) values ('Maroon');
insert into poscondiciones (poscondiciones) values ('Maroon');
insert into poscondiciones (poscondiciones) values ('Violet');
insert into poscondiciones (poscondiciones) values ('Indigo');
insert into poscondiciones (poscondiciones) values ('Red');
insert into poscondiciones (poscondiciones) values ('Green');
insert into poscondiciones (poscondiciones) values ('Teal');
insert into poscondiciones (poscondiciones) values ('Purple');
insert into poscondiciones (poscondiciones) values ('Crimson');
insert into poscondiciones (poscondiciones) values ('Puce');
insert into poscondiciones (poscondiciones) values ('Turquoise');
insert into poscondiciones (poscondiciones) values ('Maroon');
insert into poscondiciones (poscondiciones) values ('Mauv');
insert into poscondiciones (poscondiciones) values ('Khaki');
insert into poscondiciones (poscondiciones) values ('Maroon');
insert into poscondiciones (poscondiciones) values ('Yellow');
insert into poscondiciones (poscondiciones) values ('Orange');
insert into poscondiciones (poscondiciones) values ('Pink');
insert into poscondiciones (poscondiciones) values ('Pink');
insert into poscondiciones (poscondiciones) values ('Fuscia');
insert into poscondiciones (poscondiciones) values ('Fuscia');
insert into poscondiciones (poscondiciones) values ('Orange');
insert into poscondiciones (poscondiciones) values ('Turquoise');

insert into precondiciones (precondiciones) values ('Valmiera');
insert into precondiciones (precondiciones) values ('Yuxi');
insert into precondiciones (precondiciones) values ('Nogoonnuur');
insert into precondiciones (precondiciones) values ('Nova Olímpia');
insert into precondiciones (precondiciones) values ('Kuchinarai');
insert into precondiciones (precondiciones) values ('Ningshan Chengguanzhen');
insert into precondiciones (precondiciones) values ('Youyun');
insert into precondiciones (precondiciones) values ('Dolní Bečva');
insert into precondiciones (precondiciones) values ('Jenggawah');
insert into precondiciones (precondiciones) values ('Vaitogi');
insert into precondiciones (precondiciones) values ('Bhopālwāla');
insert into precondiciones (precondiciones) values ('Jing’an');
insert into precondiciones (precondiciones) values ('Rumelange');
insert into precondiciones (precondiciones) values ('Igarapé Miri');
insert into precondiciones (precondiciones) values ('Panikihan');
insert into precondiciones (precondiciones) values ('Aleg');
insert into precondiciones (precondiciones) values ('Shimabara');
insert into precondiciones (precondiciones) values ('Petropavlovsk');
insert into precondiciones (precondiciones) values ('Duayaw Nkwanta');
insert into precondiciones (precondiciones) values ('Hamilton');
insert into precondiciones (precondiciones) values ('Dagang');
insert into precondiciones (precondiciones) values ('Lac La Biche');
insert into precondiciones (precondiciones) values ('Fukumitsu');
insert into precondiciones (precondiciones) values ('Vinha');
insert into precondiciones (precondiciones) values ('Fengshuling');
=======

delete from RequisitosEntity;


insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Mueller, Okuneva and Murphy', 'Frederick Abramov', 'Black-cheeked waxbill', 1, 0, 'Suspendisse potenti. In eleifend quam a odio.', 2, 'Multi-channelled radical toolset');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Hessel, Dooley and Schuppe', 'Rosetta Raubenheim', 'Glider, sugar', 2, 1, 'Curabitur in libero ut massa volutpat convallis.', 2, 'Managed encompassing task-force');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Rowe and Sons', 'Weylin Haysom', 'Macaw, green-winged', 3, 0, 'Praesent id massa id nisl venenatis lacinia.', 3, 'Versatile bifurcated framework');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Robel-Treutel', 'Ray Crosston', 'Russian dragonfly', 4, 1, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 4, 'Triple-buffered disintermediate strategy');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Kozey-Bode', 'Roman Gowland', 'Blackbuck', 5, 0, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3, 'Decentralized bandwidth-monitored success');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Mante-Wilderman', 'Todd Boise', 'Bonnet macaque', 6, 1, 'Fusce consequat.', 4, 'Right-sized holistic monitoring');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Cassin-Schmitt', 'Ericka Sandford', 'Giant heron', 7, 1, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4, 'Configurable stable capacity');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Hirthe-Goyette', 'Kevan Petersen', 'African jacana', 8, 0, 'Praesent lectus.', 4, 'Expanded human-resource capability');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Shields LLC', 'Bonni Christophers', 'Camel, dromedary', 9, 0, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 4, 'Pre-emptive client-server pricing structure');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Shanahan Group', 'Angel Lared', 'Asian openbill', 10, 0, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 3, 'Profound optimal projection');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Crooks-Powlowski', 'Stevena Amery', 'Ring-tailed lemur', 11, 0, 'Morbi a ipsum. Integer a nibh.', 3, 'Secured asymmetric definition');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Volkman-Ward', 'Siward Booker', 'Bleeding heart monkey', 12, 1, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'Expanded zero defect productivity');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Turner and Sons', 'Adara McKniely', 'Honey badger', 13, 1, 'Morbi non quam nec dui luctus rutrum.', 4, 'Customer-focused leading edge access');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Welch and Sons', 'Wilma Smickle', 'Three-banded plover', 14, 1, 'Duis at velit eu est congue elementum.', 2, 'User-friendly impactful benchmark');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('West, Predovic and Schiller', 'Margot Gregorio', 'Golden brush-tailed possum', 15, 1, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, 'Organized bifurcated firmware');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bahringer and Sons', 'Meade Coulston', 'Asian foreset tortoise', 16, 1, 'Suspendisse potenti.', 3, 'Future-proofed demand-driven architecture');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Durgan, Kertzmann and Cummings', 'Tiffany Antusch', 'Blue catfish', 17, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0, 'Virtual coherent paradigm');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Lesch, Bogan and Fritsch', 'Cam McNiff', 'Bandicoot, long-nosed', 18, 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 4, 'Seamless scalable hardware');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Kemmer, Cremin and Haag', 'Fayette Pattullo', 'African elephant', 19, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 3, 'Adaptive fresh-thinking alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('MacGyver-Kozey', 'Jacob MacNalley', 'Wild boar', 20, 1, 'Proin eu mi.', 4, 'User-centric homogeneous alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bogisich and Sons', 'Trixi Gouly', 'Llama', 21, 0, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 0, 'Assimilated secondary methodology');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bogan-Harvey', 'Margarette Matyushenko', 'Madagascar hawk owl', 22, 1, 'Fusce consequat. Nulla nisl.', 2, 'Seamless zero tolerance service-desk');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Runolfsdottir Group', 'Austin Ruller', 'Sungazer, yellow-brown', 23, 1, 'Integer ac leo. Pellentesque ultrices mattis odio.', 4, 'Optional high-level alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Trantow, Ratke and Luettgen', 'Jillayne Duding', 'Goose, snow', 24, 1, 'Nullam varius.', 4, 'Managed real-time methodology');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bashirian and Sons', 'Murry McQuarrie', 'Mynah, common', 25, 1, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 3, 'Organic maximized toolset');
>>>>>>> bb97661b2b33a7ffa83d9ad0c2d421a3a5680b63
