
delete from RequisitosEntity;


insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Mueller, Okuneva and Murphy', 'Frederick Abramov', 'Black-cheeked waxbill', 1, 0, 'Suspendisse potenti. In eleifend quam a odio.', 2, 'Multi-channelled radical toolset');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Hessel, Dooley and Schuppe', 'Rosetta Raubenheim', 'Glider, sugar', 2, 1, 'Curabitur in libero ut massa volutpat convallis.', 2, 'Managed encompassing task-force');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Rowe and Sons', 'Weylin Haysom', 'Macaw, green-winged', 3, 0, 'Praesent id massa id nisl venenatis lacinia.', 3, 'Versatile bifurcated framework');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Robel-Treutel', 'Ray Crosston', 'Russian dragonfly', 4, 1, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 4, 'Triple-buffered disintermediate strategy');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Kozey-Bode', 'Roman Gowland', 'Blackbuck', 5, 0, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3, 'Decentralized bandwidth-monitored success');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Mante-Wilderman', 'Todd Boise', 'Bonnet macaque', 6, 1, 'Fusce consequat.', 4, 'Right-sized holistic monitoring');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Cassin-Schmitt', 'Ericka Sandford', 'Giant heron', 7, 1, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4, 'Configurable stable capacity');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Hirthe-Goyette', 'Kevan Petersen', 'African jacana', 8, 0, 'Praesent lectus.', 4, 'Expanded human-resource capability');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Shields LLC', 'Bonni Christophers', 'Camel, dromedary', 9, 0, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 4, 'Pre-emptive client-server pricing structure');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Shanahan Group', 'Angel Lared', 'Asian openbill', 10, 0, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 3, 'Profound optimal projection');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Crooks-Powlowski', 'Stevena Amery', 'Ring-tailed lemur', 11, 0, 'Morbi a ipsum. Integer a nibh.', 3, 'Secured asymmetric definition');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Volkman-Ward', 'Siward Booker', 'Bleeding heart monkey', 12, 1, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 'Expanded zero defect productivity');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Turner and Sons', 'Adara McKniely', 'Honey badger', 13, 1, 'Morbi non quam nec dui luctus rutrum.', 4, 'Customer-focused leading edge access');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Welch and Sons', 'Wilma Smickle', 'Three-banded plover', 14, 1, 'Duis at velit eu est congue elementum.', 2, 'User-friendly impactful benchmark');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('West, Predovic and Schiller', 'Margot Gregorio', 'Golden brush-tailed possum', 15, 1, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, 'Organized bifurcated firmware');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bahringer and Sons', 'Meade Coulston', 'Asian foreset tortoise', 16, 1, 'Suspendisse potenti.', 3, 'Future-proofed demand-driven architecture');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Durgan, Kertzmann and Cummings', 'Tiffany Antusch', 'Blue catfish', 17, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 0, 'Virtual coherent paradigm');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Lesch, Bogan and Fritsch', 'Cam McNiff', 'Bandicoot, long-nosed', 18, 1, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 4, 'Seamless scalable hardware');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Kemmer, Cremin and Haag', 'Fayette Pattullo', 'African elephant', 19, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 3, 'Adaptive fresh-thinking alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('MacGyver-Kozey', 'Jacob MacNalley', 'Wild boar', 20, 1, 'Proin eu mi.', 4, 'User-centric homogeneous alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bogisich and Sons', 'Trixi Gouly', 'Llama', 21, 0, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 0, 'Assimilated secondary methodology');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bogan-Harvey', 'Margarette Matyushenko', 'Madagascar hawk owl', 22, 1, 'Fusce consequat. Nulla nisl.', 2, 'Seamless zero tolerance service-desk');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Runolfsdottir Group', 'Austin Ruller', 'Sungazer, yellow-brown', 23, 1, 'Integer ac leo. Pellentesque ultrices mattis odio.', 4, 'Optional high-level alliance');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Trantow, Ratke and Luettgen', 'Jillayne Duding', 'Goose, snow', 24, 1, 'Nullam varius.', 4, 'Managed real-time methodology');
insert into RequisitosEntity (fuente, autor, descripcion, importancia, estabilidad, comentariosAdicionales, tipo, nombre) values ('Bashirian and Sons', 'Murry McQuarrie', 'Mynah, common', 25, 1, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 3, 'Organic maximized toolset');
